[package]
name = "app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpui.workspace = true
gpui_platform.workspace = true
design_system = { path = "../design_system" }
imagesize = "0.14.0"
pulldown-cmark = { version = "0.13.0", default-features = false }
tempfile = "3.20.0"
walkdir = "2.5"
